### ISSUE TITLE
Is this a fork of PG?

### ISSUE THREAD

**Issue by MichaelDBA** [pgspider/pgspider_ext#2]
I understand extensions for PostgreSQL, but to get this extension to work, you have to start pgspider, not postgres.  So what does that really mean?  Is this a fork of PG?  Can't we get this to work just starting community postgres and installing the extension?

**Comment by t-kataym** [comment]
This is an extension for community postgres, not a fork of PG. You **don't** need to start [pgspider](https://github.com/pgspider/pgspider).

>  Can't we get this to work just starting community postgres and installing the extension?

You can do that. (= community potgres + pgspider_ext)

**Comment by MichaelDBA** [comment]
I’m still not getting it: what is the point then of starting pgspider per the readme instructions?

**Comment by t-kataym** [comment]
As described at the beginning of readme, "We call PostgreSQL installed pgspider_ext as "PGSpider".".

Anyway, I'm sorry it's hard to understand. I think you can understand if you read "Start PGSpider" as "Start community PostgreSQL".

**Comment by MichaelDBA** [comment]
oh my gosh, did i completely misread the README or what!  Of course you are correct.  My bad.

Hate to be the first bad issue to be created!  What an exclusive club I just entered.
